### ISSUE TITLE
Bug - tests don't run from within container.

### ISSUE THREAD

**Issue by adhorrig** [adhorrig/flask-rest-api#7]
Tests will always fail when running `python tests.py` or `python -m unittest discover`  as the app is running inside the container and these commands are external. Example output;

```
OperationalError: (sqlite3.OperationalError) no such table: car [SQL: u'SELECT car.id AS car_id, car.make AS car_make, car.model AS car_model, car.year AS car_year, car.chasis_id AS car_chasis_id, car.price AS car_price, car.last_updated AS car_last_updated \nFROM car'] (Background on this error at: http://sqlalche.me/e/e3q8)
F
======================================================================
ERROR: test_response (__main__.TestAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 31, in test_response
    data = json.loads(result.get_data(as_text=True))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

======================================================================
FAIL: test_create (__main__.TestAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 48, in test_create
    self.assertEqual(response.status_code, 200)
AssertionError: 500 != 200

======================================================================
FAIL: test_status_code (__main__.TestAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 26, in test_status_code
    self.assertEqual(result.status_code, 200)
AssertionError: 500 != 200

----------------------------------------------------------------------
Ran 3 tests in 0.045s

FAILED (failures=2, errors=1)
```

**Comment by adhorrig** [comment]
Documentation error - fix merged
